[package]
name = "longan-nano-blinky-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv = "0.10.1"
riscv-rt =  "0.11.0"

embedded-hal = "0.2.7"
gd32vf103xx-hal = "0.5.0"

longan-nano = "0.3.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 3
